### ISSUE TITLE
Invalid Token Exception while accessing okta SDK

### ISSUE THREAD

**Issue by lingpri** [lingpri/okta#1]
Exception in thread "main" com.okta.sdk.resource.ResourceException: HTTP 401, Okta E0000011 (Invalid token provided), ErrorId oaeh-VYtk-NTROiVSomvvk_-Q
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:453)
	at com.okta.sdk.impl.ds.DefaultDataStore.lambda$getResourceData$0(DefaultDataStore.java:193)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:47)
	at com.okta.sdk.impl.ds.cache.WriteCacheFilter.filter(WriteCacheFilter.java:34)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.cache.ReadCacheFilter.filter(ReadCacheFilter.java:42)
	at com.okta.sdk.impl.ds.DefaultFilterChain.filter(DefaultFilterChain.java:52)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResourceData(DefaultDataStore.java:205)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:174)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:169)
	at com.okta.sdk.impl.ds.DefaultDataStore.getResource(DefaultDataStore.java:165)
	at com.okta.sdk.impl.client.DefaultClient.listUsers(DefaultClient.java:793)
	at OktaSyslog.main(OktaSyslog.java:26)

**Comment by lingpri** [comment]
revoked  the token and the issue got resolved , after using a new token.

**Comment by W501638** [comment]
any one please share the solution,i am facing same error even i use new token.
